import type { ScanResult } from "../types.js";
import { slugify } from "../app/appData.js";
import { buildLearningData, type AppLearningData, type ExplanationDepth } from "../app/explanationData.js";
import { summarizeProjectMemory, type ProjectMemory } from "../memory/projectMemory.js";

export type HandoffAgent = "codex" | "claude" | "cursor" | "copy";

export type HandoffTaskType = "build-feature" | "fix-bug" | "explain-code" | "refactor" | "write-tests" | "review";

export interface HandoffRequest {
  agent: HandoffAgent;
  taskType: HandoffTaskType;
  goal: string;
  scope?: string;
  memory?: ProjectMemory;
  explanationDepth?: ExplanationDepth;
}

export interface HandoffResult {
  slug: string;
  agent: HandoffAgent;
  taskType: HandoffTaskType;
  goal: string;
  scope: string | null;
  relevantFiles: string[];
  prompt: string;
  markdown: string;
}

export function buildHandoff(scan: ScanResult, request: HandoffRequest): HandoffResult {
  const goal = normalizeGoal(request.goal);
  const scope = request.scope?.trim() || null;
  const slug = slugify(goal).slice(0, 80) || "handoff-task";
  const relevantFiles = collectRelevantFiles(scan, scope);
  const agentLabel = agentDisplayName(request.agent);
  const taskLabel = taskTypeLabel(request.taskType);
  const learning = buildLearningData(scan);
  const explanationDepth = request.explanationDepth ?? null;
  const explanationLine = explanationDepth
    ? `Use ${depthLabel(explanationDepth)}-level explanations when explaining code, tradeoffs, and validation.`
    : "";
  const prompt = [
    `Use ${agentLabel} to ${taskLabel.toLowerCase()} in this local repo.`,
    "",
    `Goal: ${goal}`,
    `Repo: ${scan.profile.repoRoot}`,
    scope ? `Scope: ${scope}` : "Scope: use the bounded context below",
    explanationLine,
    "",
    "Read the handoff packet first, then inspect only the relevant files unless the task requires expanding scope.",
    request.memory ? "Use the Project Memory section for recent notes, scan changes, and validation history." : "",
    "Do not edit protected paths or generated dependency/build folders.",
    "Run the listed validation checks before reporting completion."
  ].filter(Boolean).join("\n");

  return {
    slug,
    agent: request.agent,
    taskType: request.taskType,
    goal,
    scope,
    relevantFiles,
    prompt,
    markdown: renderHandoffMarkdown(scan, {
      agentLabel,
      taskLabel,
      goal,
      scope,
      relevantFiles,
      prompt,
      memory: request.memory,
      learning,
      explanationDepth
    })
  };
}

function renderHandoffMarkdown(
  scan: ScanResult,
  context: {
    agentLabel: string;
    taskLabel: string;
    goal: string;
    scope: string | null;
    relevantFiles: string[];
    prompt: string;
    memory?: ProjectMemory;
    learning: AppLearningData;
    explanationDepth: ExplanationDepth | null;
  }
): string {
  return [
    `# Agent Handoff: ${context.goal}`,
    "",
    "Generated by ProNav from a read-only local repo scan.",
    "",
    "## Plain-English Goal",
    "",
    context.goal,
    "",
    "## Coding Agent",
    "",
    `- Agent: ${context.agentLabel}`,
    `- Task type: ${context.taskLabel}`,
    `- Repo: \`${scan.profile.repoRoot}\``,
    `- Project type: \`${scan.detection.type}\``,
    `- Scope: ${context.scope ? `\`${context.scope}\`` : "bounded context below"}`,
    "",
    "## Friendly Project Context",
    "",
    `- Files scanned: ${scan.generic.totalFiles}`,
    `- Documents found: ${scan.documents.totalDocuments}`,
    `- Detected capabilities: ${scan.detection.detectedCapabilities.join(", ")}`,
    `- Main language groups: ${Object.entries(scan.generic.languageCounts)
      .slice(0, 6)
      .map(([name, count]) => `${name} (${count})`)
      .join(", ") || "none detected"}`,
    "",
    "## Relevant Files",
    "",
    ...bulletList(context.relevantFiles, "No narrow file matches were found. Start with the repo map and docs."),
    "",
    "## Project Documents",
    "",
    ...bulletList(scan.documents.files.slice(0, 10).map((file) => file.path), "No documents detected."),
    ...renderExplanationContext(context.learning, context.explanationDepth, context.relevantFiles),
    ...renderMemorySection(context.memory),
    "",
    "## Validation Checks",
    "",
    ...bulletList(scan.profile.validationCommands, "No validation commands configured."),
    "",
    "## Protected Paths",
    "",
    "- Do not edit protected paths or generated dependency/build folders unless the user explicitly asks.",
    ...bulletList(scan.profile.protectedPaths, "No protected paths configured."),
    "",
    "## Ready-To-Paste Prompt",
    "",
    "```text",
    context.prompt,
    "```"
  ].join("\n");
}

function renderExplanationContext(
  learning: AppLearningData,
  depth: ExplanationDepth | null,
  relevantFiles: string[]
): string[] {
  if (!depth) return [];

  const relevant = new Set(relevantFiles);
  const concepts = learning.concepts.filter((concept) => concept.paths.some((path) => relevant.has(path))).slice(0, 8);
  return [
    "",
    "## Explanation Context",
    "",
    `- Explanation depth: ${depthLabel(depth)}`,
    `- Project explanation: ${learning.projectExplanation[depth]}`,
    "",
    "### Detected Concepts",
    "",
    ...plainBulletList(
      concepts.map((concept) => `${concept.label}: ${concept.description} Paths: ${concept.paths.slice(0, 3).join(", ")}`),
      "No high-signal concepts were detected in the bounded file list."
    )
  ];
}

function collectRelevantFiles(scan: ScanResult, scope: string | null): string[] {
  const candidates = [
    ...Object.values(scan.features).flatMap((feature) => feature.files.map((file) => file.path)),
    ...scan.generic.sampleFiles,
    ...scan.documents.files.map((file) => file.path)
  ];
  const filtered = scope ? candidates.filter((path) => path.startsWith(scope) || path.includes(scope)) : candidates;
  const narrowed = filtered.length > 0 ? filtered : candidates;

  return [...new Set(narrowed)].slice(0, 30);
}

function normalizeGoal(goal: string): string {
  const value = goal.trim();
  if (!value) {
    throw new Error("Handoff goal is required.");
  }

  return value;
}

function agentDisplayName(agent: HandoffAgent): string {
  switch (agent) {
    case "codex":
      return "Codex";
    case "claude":
      return "Claude Code";
    case "cursor":
      return "Cursor";
    case "copy":
      return "Copy Prompt";
  }
}

function taskTypeLabel(taskType: HandoffTaskType): string {
  switch (taskType) {
    case "build-feature":
      return "Build Feature";
    case "fix-bug":
      return "Fix Bug";
    case "explain-code":
      return "Explain Code";
    case "refactor":
      return "Refactor";
    case "write-tests":
      return "Write Tests";
    case "review":
      return "Review";
  }
}

function depthLabel(depth: ExplanationDepth): string {
  switch (depth) {
    case "builder":
      return "Builder";
    case "developer":
      return "Developer";
    case "senior":
      return "Senior";
  }
}

function bulletList(values: string[], emptyText: string): string[] {
  return values.length === 0 ? [`- ${emptyText}`] : values.map((value) => `- \`${value}\``);
}

function renderMemorySection(memory: ProjectMemory | undefined): string[] {
  if (!memory) return [];

  const hasMemory =
    memory.scans.length > 0 || memory.validations.length > 0 || memory.handoffs.length > 0 || memory.notes.length > 0;
  if (!hasMemory) return [];

  const summary = summarizeProjectMemory(memory);
  return [
    "",
    "## Project Memory",
    "",
    ...renderScanMemory(summary),
    `- Validation history: ${summary.validationCounts.passed} passed, ${summary.validationCounts.failed} failed, ${summary.validationCounts.timedOut} timed out`,
    "",
    "### Recent Notes",
    "",
    ...plainBulletList(
      memory.notes.slice(0, 5).map((note) => `${formatMemoryDate(note.createdAt)}: ${note.text}`),
      "No notes saved yet."
    ),
    "",
    "### Recent Validation Runs",
    "",
    ...plainBulletList(memory.validations.slice(0, 5).map(renderValidationMemory), "No validation runs recorded yet."),
    "",
    "### Recent Handoffs",
    "",
    ...plainBulletList(memory.handoffs.slice(0, 5).map(renderHandoffMemory), "No prior handoffs recorded yet.")
  ];
}

function renderScanMemory(summary: ReturnType<typeof summarizeProjectMemory>): string[] {
  if (!summary.latestScan) {
    return ["- No scan history recorded yet."];
  }

  if (!summary.previousScan || !summary.scanChange) {
    return [`- Latest scan: ${summary.latestScan.files} files, ${summary.latestScan.documents} docs, ${summary.latestScan.dirtyEntries} git status entries`];
  }

  return [
    `- Files changed since last scan: ${formatSigned(summary.scanChange.files)}`,
    `- Documents changed since last scan: ${formatSigned(summary.scanChange.documents)}`,
    `- Git status entries changed since last scan: ${formatSigned(summary.scanChange.dirtyEntries)}`
  ];
}

function renderValidationMemory(validation: ProjectMemory["validations"][number]): string {
  const status = validation.timedOut ? "timed out" : validation.exitCode === 0 ? "passed" : "failed";
  return `${formatMemoryDate(validation.createdAt)}: ${validation.command} | ${status} | exit ${validation.exitCode} | ${Math.round(validation.durationMs / 1000)}s`;
}

function renderHandoffMemory(handoff: ProjectMemory["handoffs"][number]): string {
  return `${formatMemoryDate(handoff.createdAt)}: ${handoff.agent} ${handoff.taskType} | ${handoff.goal}`;
}

function plainBulletList(values: string[], emptyText: string): string[] {
  return values.length === 0 ? [`- ${emptyText}`] : values.map((value) => `- ${value}`);
}

function formatSigned(value: number): string {
  return value > 0 ? `+${value}` : String(value);
}

function formatMemoryDate(value: string): string {
  return value.slice(0, 10) || "Unknown date";
}
