import type { ScanResult } from "../types.js";
import { slugify } from "../app/appData.js";

export type HandoffAgent = "codex" | "claude" | "cursor" | "copy";

export type HandoffTaskType = "build-feature" | "fix-bug" | "explain-code" | "refactor" | "write-tests" | "review";

export interface HandoffRequest {
  agent: HandoffAgent;
  taskType: HandoffTaskType;
  goal: string;
  scope?: string;
}

export interface HandoffResult {
  slug: string;
  agent: HandoffAgent;
  taskType: HandoffTaskType;
  goal: string;
  scope: string | null;
  relevantFiles: string[];
  prompt: string;
  markdown: string;
}

export function buildHandoff(scan: ScanResult, request: HandoffRequest): HandoffResult {
  const goal = normalizeGoal(request.goal);
  const scope = request.scope?.trim() || null;
  const slug = slugify(goal).slice(0, 80) || "handoff-task";
  const relevantFiles = collectRelevantFiles(scan, scope);
  const agentLabel = agentDisplayName(request.agent);
  const taskLabel = taskTypeLabel(request.taskType);
  const prompt = [
    `Use ${agentLabel} to ${taskLabel.toLowerCase()} in this local repo.`,
    "",
    `Goal: ${goal}`,
    `Repo: ${scan.profile.repoRoot}`,
    scope ? `Scope: ${scope}` : "Scope: use the bounded context below",
    "",
    "Read the handoff packet first, then inspect only the relevant files unless the task requires expanding scope.",
    "Do not edit protected paths or generated dependency/build folders.",
    "Run the listed validation checks before reporting completion."
  ].join("\n");

  return {
    slug,
    agent: request.agent,
    taskType: request.taskType,
    goal,
    scope,
    relevantFiles,
    prompt,
    markdown: renderHandoffMarkdown(scan, {
      agentLabel,
      taskLabel,
      goal,
      scope,
      relevantFiles,
      prompt
    })
  };
}

function renderHandoffMarkdown(
  scan: ScanResult,
  context: {
    agentLabel: string;
    taskLabel: string;
    goal: string;
    scope: string | null;
    relevantFiles: string[];
    prompt: string;
  }
): string {
  return [
    `# Agent Handoff: ${context.goal}`,
    "",
    "Generated by ProNav from a read-only local repo scan.",
    "",
    "## Plain-English Goal",
    "",
    context.goal,
    "",
    "## Coding Agent",
    "",
    `- Agent: ${context.agentLabel}`,
    `- Task type: ${context.taskLabel}`,
    `- Repo: \`${scan.profile.repoRoot}\``,
    `- Project type: \`${scan.detection.type}\``,
    `- Scope: ${context.scope ? `\`${context.scope}\`` : "bounded context below"}`,
    "",
    "## Friendly Project Context",
    "",
    `- Files scanned: ${scan.generic.totalFiles}`,
    `- Documents found: ${scan.documents.totalDocuments}`,
    `- Detected capabilities: ${scan.detection.detectedCapabilities.join(", ")}`,
    `- Main language groups: ${Object.entries(scan.generic.languageCounts)
      .slice(0, 6)
      .map(([name, count]) => `${name} (${count})`)
      .join(", ") || "none detected"}`,
    "",
    "## Relevant Files",
    "",
    ...bulletList(context.relevantFiles, "No narrow file matches were found. Start with the repo map and docs."),
    "",
    "## Project Documents",
    "",
    ...bulletList(scan.documents.files.slice(0, 10).map((file) => file.path), "No documents detected."),
    "",
    "## Validation Checks",
    "",
    ...bulletList(scan.profile.validationCommands, "No validation commands configured."),
    "",
    "## Protected Paths",
    "",
    "- Do not edit protected paths or generated dependency/build folders unless the user explicitly asks.",
    ...bulletList(scan.profile.protectedPaths, "No protected paths configured."),
    "",
    "## Ready-To-Paste Prompt",
    "",
    "```text",
    context.prompt,
    "```"
  ].join("\n");
}

function collectRelevantFiles(scan: ScanResult, scope: string | null): string[] {
  const candidates = [
    ...Object.values(scan.features).flatMap((feature) => feature.files.map((file) => file.path)),
    ...scan.generic.sampleFiles,
    ...scan.documents.files.map((file) => file.path)
  ];
  const filtered = scope ? candidates.filter((path) => path.startsWith(scope) || path.includes(scope)) : candidates;
  const narrowed = filtered.length > 0 ? filtered : candidates;

  return [...new Set(narrowed)].slice(0, 30);
}

function normalizeGoal(goal: string): string {
  const value = goal.trim();
  if (!value) {
    throw new Error("Handoff goal is required.");
  }

  return value;
}

function agentDisplayName(agent: HandoffAgent): string {
  switch (agent) {
    case "codex":
      return "Codex";
    case "claude":
      return "Claude Code";
    case "cursor":
      return "Cursor";
    case "copy":
      return "Copy Prompt";
  }
}

function taskTypeLabel(taskType: HandoffTaskType): string {
  switch (taskType) {
    case "build-feature":
      return "Build Feature";
    case "fix-bug":
      return "Fix Bug";
    case "explain-code":
      return "Explain Code";
    case "refactor":
      return "Refactor";
    case "write-tests":
      return "Write Tests";
    case "review":
      return "Review";
  }
}

function bulletList(values: string[], emptyText: string): string[] {
  return values.length === 0 ? [`- ${emptyText}`] : values.map((value) => `- \`${value}\``);
}
