import type { FeatureScan, ScanResult } from "../types.js";

export function renderPlainOverview(scan: ScanResult): string {
  const projectName = displayName(scan.profile.name);
  const scripts = scriptSummaryFor(scan);
  const featureLines = Object.values(scan.features).map(
    (feature) => `- **${feature.title}:** ${feature.description} ProNav found ${feature.files.length} high-signal files.`
  );

  return [
    `# ${projectName} Plain-Language Overview`,
    "",
    "Generated by ProNav-CCL V1 from a read-only scan. This report is meant for non-coders who need a quick picture of the project without opening Unity or Supabase.",
    "",
    "## What This Project Contains",
    "",
    `- Git checkout: \`${scan.profile.repoRoot}\``,
    `- Project type: \`${scan.detection.type}\``,
    `- Detected capabilities: ${scan.detection.detectedCapabilities.map((item) => `\`${item}\``).join(", ")}`,
    `- Current branch: \`${scan.git.branch}\``,
    `- General codebase: ${scan.generic.totalFiles} scanned files across ${Object.keys(scan.generic.languageCounts).length} detected language groups.`,
    `- Script files: ${scripts.total} across ${Object.keys(scripts.typeCounts).length} detected script types.`,
    `- Documents: ${scan.documents.totalDocuments} repo documents found, with ${scan.documents.previewableDocuments} available for text preview in the app.`,
    ...(scan.detection.detectedCapabilities.includes("unity")
      ? [
          `- Unity project: \`${scan.detection.roots.unityProjectRoot ?? scan.profile.unityProjectRoot ?? scan.profile.repoRoot}\``,
          `- Unity inventory: ${scan.unity.counts.scripts} scripts, ${scan.unity.counts.prefabs} prefabs, ${scan.unity.counts.scenes} scenes, and ${scan.unity.counts.resources} resource files.`
        ]
      : ["- Unity project: not detected for this repo."]),
    ...(scan.detection.detectedCapabilities.includes("supabase")
      ? [`- Supabase backend: ${scan.supabase.migrationCount} migration files and ${scan.supabase.functionNames.length} detected SQL/RPC functions.`]
      : ["- Supabase backend: not detected for this repo."]),
    "",
    "## Main Areas",
    "",
    ...featureLines,
    "",
    "## Current Working State",
    "",
    ...bulletList(scan.git.status, "Git status is clean."),
    "",
    "## Handle With Care",
    "",
    "- ProNav writes reports inside its own repository only; the target repo is scanned read-only.",
    "- Supabase SQL is scanned as text only. No SQL is executed.",
    ...scan.profile.protectedPaths.map((protectedPath) => `- Protected path: \`${protectedPath}\``),
    "",
    "## Useful Next Step",
    "",
    "Use the technical map for developer-level routing, or generate a refactor packet for a single feature before handing work to another AI agent."
  ].join("\n");
}

export function renderTechnicalMap(scan: ScanResult): string {
  const projectName = displayName(scan.profile.name);
  const scripts = scriptSummaryFor(scan);

  return [
    `# ${projectName} Technical System Map`,
    "",
    "Generated by ProNav-CCL V1 from read-only filesystem and git scans.",
    "",
    "## Roots",
    "",
    `- Git root: \`${scan.profile.repoRoot}\``,
    `- Unity project root: \`${scan.detection.roots.unityProjectRoot ?? scan.profile.unityProjectRoot ?? "not detected"}\``,
    `- Project type: \`${scan.detection.type}\``,
    `- Detected capabilities: ${scan.detection.detectedCapabilities.map((item) => `\`${item}\``).join(", ")}`,
    "",
    "## Git",
    "",
    `- Branch: \`${scan.git.branch}\``,
    "- Status:",
    ...indentedList(scan.git.status, "clean"),
    "- Recent commits:",
    ...indentedList(scan.git.recentCommits, "none detected"),
    "- Remotes:",
    ...indentedList(scan.git.remotes, "none detected"),
    "",
    "## Generic Code Map",
    "",
    `- Files scanned: ${scan.generic.totalFiles}`,
    "- Language/file groups:",
    ...indentedKeyValues(scan.generic.languageCounts, "none detected"),
    `- Script files: ${scripts.total}`,
    "- Script types:",
    ...indentedKeyValues(scripts.typeCounts, "none detected"),
    "- Script samples:",
    ...indentedList(scripts.samples.slice(0, 40), "none detected"),
    "- Top directories:",
    ...indentedList(scan.generic.topDirectories.map((item) => `${item.path}: ${item.count}`), "none detected"),
    "- Manifests:",
    ...indentedList(scan.generic.manifests, "none detected"),
    "",
    "## Documents",
    "",
    `- Documents found: ${scan.documents.totalDocuments}`,
    `- Text-previewable documents: ${scan.documents.previewableDocuments}`,
    "- Key documents:",
    ...indentedList(scan.documents.files.slice(0, 40).map((file) => file.path), "none detected"),
    "",
    "## Node",
    "",
    `- Package manager: \`${scan.node.packageManager ?? "not detected"}\``,
    "- Scripts:",
    ...indentedList(scan.node.scripts, "none detected"),
    "- Framework/library hints:",
    ...indentedList(scan.node.frameworks, "none detected"),
    "",
    "## Unity Inventory",
    "",
    `- Scenes: ${scan.unity.counts.scenes}`,
    `- Prefabs: ${scan.unity.counts.prefabs}`,
    `- Unity script assets: ${scan.unity.counts.scripts}`,
    `- Resources: ${scan.unity.counts.resources}`,
    `- ProjectSettings files: ${scan.unity.counts.projectSettings}`,
    "",
    "### Key Scenes",
    ...indentedList(scan.unity.scenes, "none detected"),
    "",
    "### Key Prefabs",
    ...indentedList(scan.unity.prefabs, "none detected"),
    "",
    "### Key Scripts",
    ...indentedList(scan.unity.scripts, "none detected"),
    "",
    "### SEL Directories",
    ...indentedList(scan.unity.selDirectories, "none detected"),
    "",
    "## Supabase",
    "",
    `- Migration files: ${scan.supabase.migrationCount}`,
    "- Recent/known migrations:",
    ...indentedList(scan.supabase.migrations.slice(-30), "none detected"),
    "- Detected SQL/RPC function names:",
    ...indentedList(scan.supabase.functionNames.slice(0, 60), "none detected"),
    "- Supabase docs/seeds:",
    ...indentedList(scan.supabase.docs, "none detected"),
    "",
    "## WordPress",
    "",
    `- wp-config.php present: ${scan.wordpress.hasWpConfig ? "yes" : "no"}`,
    "- Content roots:",
    ...indentedList(scan.wordpress.contentRoots, "none detected"),
    "- Themes:",
    ...indentedList(scan.wordpress.themes, "none detected"),
    "- Plugins:",
    ...indentedList(scan.wordpress.plugins, "none detected"),
    "",
    "## Feature Areas",
    "",
    ...Object.values(scan.features).flatMap(renderFeatureSummary),
    "",
    "## Validation Commands",
    "",
    ...indentedList(scan.profile.validationCommands, "none configured"),
    "",
    "## Protected Paths",
    "",
    ...indentedList(scan.profile.protectedPaths, "none configured")
  ].join("\n");
}

export function renderRefactorPacket(scan: ScanResult, featureId: string): string {
  const feature = scan.features[featureId];
  if (!feature) {
    throw new Error(`Unknown feature '${featureId}'. Available features: ${Object.keys(scan.features).join(", ")}`);
  }

  const projectName = displayName(scan.profile.name);
  const scripts = scriptSummaryFor(scan);

  return [
    `# ${projectName} Refactor Packet: ${feature.title}`,
    "",
    "Generated by ProNav-CCL V1 for bounded AI/refactor work. Treat this packet as context, not permission for ProNav to edit the target repo.",
    "",
    "## Feature Goal",
    "",
    feature.description,
    "",
    "## Boundaries",
    "",
    `- Work should be scoped to \`${feature.id}\` unless the user expands scope.`,
    "- Preserve backend-authoritative behavior when Supabase/RPC paths are involved.",
    "- Do not edit generated Unity folders or local secret/config folders.",
    "- Reports belong in ProNav-CCL, never inside the scanned target repo.",
    "",
    "## Relevant Files",
    "",
    ...featureFileList(feature),
    "",
    "## Backend Context",
    "",
    `- Supabase migrations detected: ${scan.supabase.migrationCount}`,
    "- SQL/RPC names detected in migrations:",
    ...indentedList(scan.supabase.functionNames.slice(0, 40), "none detected"),
    "- Supabase docs/seeds:",
    ...indentedList(scan.supabase.docs, "none detected"),
    "",
    "## Project Context",
    "",
    `- Project type: \`${scan.detection.type}\``,
    `- Files scanned: ${scan.generic.totalFiles}`,
    `- Script files detected: ${scripts.total}`,
    `- Documents found: ${scan.documents.totalDocuments}`,
    "- Detected capabilities:",
    ...indentedList(scan.detection.detectedCapabilities, "generic only"),
    "- Manifests:",
    ...indentedList(scan.generic.manifests, "none detected"),
    "",
    "## Unity Context",
    "",
    "- Key scenes:",
    ...indentedList(scan.unity.scenes, "none detected"),
    "- Key prefabs:",
    ...indentedList(scan.unity.prefabs.slice(0, 15), "none detected"),
    "",
    "## Required Validation",
    "",
    ...indentedList(scan.profile.validationCommands, "none configured"),
    "",
    "## Protected Paths",
    "",
    ...indentedList(scan.profile.protectedPaths, "none configured"),
    "",
    "## Current Git State",
    "",
    `- Branch: \`${scan.git.branch}\``,
    "- Status:",
    ...indentedList(scan.git.status, "clean")
  ].join("\n");
}

function renderFeatureSummary(feature: FeatureScan): string[] {
  return [
    `### ${feature.title}`,
    "",
    feature.description,
    "",
    `- Candidate files scanned: ${feature.totalCandidates}`,
    `- High-signal files: ${feature.files.length}`,
    ...feature.files.slice(0, 15).map((file) => `- \`${file.path}\` (${file.matchedKeywords.join(", ")})`),
    ""
  ];
}

function featureFileList(feature: FeatureScan): string[] {
  if (feature.files.length === 0) {
    return ["- No high-signal files matched this feature profile."];
  }

  return feature.files.map((file) => `- \`${file.path}\` - score ${file.score}; keywords: ${file.matchedKeywords.join(", ")}`);
}

function scriptSummaryFor(scan: ScanResult): NonNullable<ScanResult["generic"]["scripts"]> {
  if (scan.generic.scripts) {
    return scan.generic.scripts;
  }

  const scriptLanguages = new Set([
    "C#",
    "Clojure",
    "ClojureScript",
    "Dart",
    "Elixir",
    "Erlang",
    "F#",
    "Go",
    "Java",
    "JavaScript",
    "JavaScript React",
    "Kotlin",
    "Lua",
    "PHP",
    "Perl",
    "PowerShell",
    "Python",
    "R",
    "Ruby",
    "Rust",
    "Scala",
    "Shell",
    "SQL",
    "Svelte",
    "Swift",
    "TypeScript",
    "TypeScript React",
    "Vue"
  ]);
  const typeCounts = Object.fromEntries(Object.entries(scan.generic.languageCounts).filter(([language]) => scriptLanguages.has(language)));
  const total = Object.values(typeCounts).reduce((sum, count) => sum + count, 0) || scan.unity.counts.scripts;
  const samples = [...new Set([...scan.unity.scripts, ...scan.generic.sampleFiles])].slice(0, 80);
  return { total, typeCounts, samples };
}

function bulletList(values: string[], emptyText: string): string[] {
  return values.length === 0 ? [`- ${emptyText}`] : values.map((value) => `- \`${value}\``);
}

function indentedList(values: string[], emptyText: string): string[] {
  return values.length === 0 ? [`  - ${emptyText}`] : values.map((value) => `  - \`${value}\``);
}

function indentedKeyValues(values: Record<string, number>, emptyText: string): string[] {
  const entries = Object.entries(values);
  return entries.length === 0 ? [`  - ${emptyText}`] : entries.map(([key, value]) => `  - \`${key}: ${value}\``);
}

function displayName(name: string): string {
  return name
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join(" ");
}
